name: finsight_vn
version: 1.0.0
config-version: 2

profile: finsight_vn
model-paths: ["dbt/models"]
test-paths: ["dbt/tests"]
macro-paths: ["dbt/macros"]
clean-targets: ["target", "dbt_packages"]

models:
  finsight_vn:
    staging:
      +materialized: view
      +schema: staging
    marts:
      +materialized: table
      +schema: analytics
